FROM mcr.microsoft.com/dotnet/core/sdk:3.1.102-bionic

ARG DYALOG_DEB_PKG

ADD ./$DYALOG_DEB_PKG /
RUN dpkg -i /$DYALOG_DEB_PKG

ENV RIDE_INIT="SERVE:*:4502"
ENV DYALOG="/opt/mdyalog/18.0/64/unicode"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$DYALOG"

CMD $DYALOG/dyalog